# Generated by Django 5.2.5 on 2025-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_ordermodel_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='card_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='card_number',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
