# Generated by Django 5.2.5 on 2025-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Decor', 'Decor')], default='Electronics', max_length=50),
            preserve_default=False,
        ),
    ]
